---
title: "NCAA_Model"
author: "Quinn Schroeder"
date: "11/19/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

# Load in libraries 
```{r}
library('fmsb')
library(ALSM)
library(car)
library(onewaytests)
library(MASS)
library(lmridge)
library(leaps)
library(caret)
library(dplyr)
library(pacman)
library(ggplot2)
library(rvest)
library(plyr)
library(stringr)
library(collegeballR)
library(magrittr)
library(tm)
```

# Scrape Data
```{r}
#Basic
years = c(2011:2021)
urls = list()
for (i in 1:length(years)) {
  url = paste0('https://www.sports-reference.com/cbb/seasons/', years[i],'-school-stats.html')
  urls[[i]] = url
}

tbl = list()
years = 2011
j = 1
for (j in seq_along(urls)) {
  tbl[[j]] = urls[[j]] %>%
    read_html() %>%
    html_node("table") %>%
    html_table() 
  tbl[[j]]$Year = years
  years = years+1
}

NCAABasic = ldply(tbl, data.frame)

NCAABasic = NCAABasic[-1,c(-1,-9,-12,-15,-18,-21,-22)]

names(NCAABasic)[names(NCAABasic) == "Var.2"] <- "School"
names(NCAABasic)[names(NCAABasic) == "Overall"] <- "G"
names(NCAABasic)[names(NCAABasic) == "Overall.1"] <- "W"
names(NCAABasic)[names(NCAABasic) == "Overall.2"] <- "L"
names(NCAABasic)[names(NCAABasic) == "Overall.3"] <- "WinPer"
names(NCAABasic)[names(NCAABasic) == "Overall.4"] <- "SRS"
names(NCAABasic)[names(NCAABasic) == "Overall.5"] <- "SOS"
names(NCAABasic)[names(NCAABasic) == "Conf."] <- "ConW"
names(NCAABasic)[names(NCAABasic) == "Conf..1"] <- "ConL"
names(NCAABasic)[names(NCAABasic) == "Home"] <- "HomeW"
names(NCAABasic)[names(NCAABasic) == "Home.1"] <- "HomeL"
names(NCAABasic)[names(NCAABasic) == "Away"] <- "AwayW"
names(NCAABasic)[names(NCAABasic) == "Away.1"] <- "AwayL"
names(NCAABasic)[names(NCAABasic) == "Points"] <- "TotPTS"
names(NCAABasic)[names(NCAABasic) == "Points.1"] <- "OppPTS"
names(NCAABasic)[names(NCAABasic) == "Totals"] <- "MP"
names(NCAABasic)[names(NCAABasic) == "Totals.1"] <- "FG"
names(NCAABasic)[names(NCAABasic) == "Totals.2"] <- "FGA"
names(NCAABasic)[names(NCAABasic) == "Totals.3"] <- "FGPer"
names(NCAABasic)[names(NCAABasic) == "Totals.4"] <- "X3P"
names(NCAABasic)[names(NCAABasic) == "Totals.5"] <- "X3PA"
names(NCAABasic)[names(NCAABasic) == "Totals.6"] <- "X3Per"
names(NCAABasic)[names(NCAABasic) == "Totals.7"] <- "FT"
names(NCAABasic)[names(NCAABasic) == "Totals.8"] <- "FTA"
names(NCAABasic)[names(NCAABasic) == "Totals.9"] <- "FTPer"
names(NCAABasic)[names(NCAABasic) == "Totals.10"] <- "ORB"
names(NCAABasic)[names(NCAABasic) == "Totals.11"] <- "TRB"
names(NCAABasic)[names(NCAABasic) == "Totals.12"] <- "AST"
names(NCAABasic)[names(NCAABasic) == "Totals.13"] <- "STL"
names(NCAABasic)[names(NCAABasic) == "Totals.14"] <- "BLK"
names(NCAABasic)[names(NCAABasic) == "Totals.15"] <- "TOV"
names(NCAABasic)[names(NCAABasic) == "Totals.16"] <- "PF"

NCAABasic <- NCAABasic[!grepl("School", NCAABasic$School),]
NCAABasic <- NCAABasic[!grepl("Overall", NCAABasic$G),]
NCAABasic$School <- str_remove(NCAABasic$School, "NCAA")
NCAABasic <- NCAABasic[!grepl(0, NCAABasic$G),]

NCAABasic$Season <- paste(NCAABasic$School, NCAABasic$Year, sep=" ")
NCAABasic = NCAABasic[,c(33,1,32,2:31)]

#Basic Opponent

years = c(2011:2021)
urls = list()
for (i in 1:length(years)) {
  url = paste0('https://www.sports-reference.com/cbb/seasons/', years[i],'-opponent-stats.html')
  urls[[i]] = url
}

tbl = list()
years = 2011
j = 1
for (j in seq_along(urls)) {
  tbl[[j]] = urls[[j]] %>%
    read_html() %>%
    html_nodes("table") %>%
    html_table() 
  tbl[[j]]$Year = years
  years = years + 1
}

NCAABasicOpp = ldply(tbl, data.frame)
NCAABasicOpp = NCAABasicOpp[,c(-1,-4:-22)]

names(NCAABasicOpp)[names(NCAABasicOpp) == "Var.2"] <- "School"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Overall"] <- "G"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.1"] <- "OFG"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.2"] <- "OFGA"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.3"] <- "OFGPer"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.4"] <- "O3P"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.5"] <- "O3PA"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.6"] <- "O3Per"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.7"] <- "OFT"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.8"] <- "OFTA"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.9"] <- "OFTPer"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.10"] <- "OORB"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.11"] <- "OTRB"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.12"] <- "OAST"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.13"] <- "OSTL"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.14"] <- "OBLK"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.15"] <- "OTOV"
names(NCAABasicOpp)[names(NCAABasicOpp) == "Opponent.16"] <- "OPF"

NCAABasicOpp <- NCAABasicOpp[!grepl("School", NCAABasicOpp$School),]
NCAABasicOpp <- NCAABasicOpp[!grepl("Overall", NCAABasicOpp$G),]
NCAABasicOpp$School <- str_remove(NCAABasicOpp$School, "NCAA")
NCAABasicOpp <- NCAABasicOpp[!grepl(0, NCAABasicOpp$G),]
NCAABasicOpp = NCAABasicOpp[,c(-2)]

NCAABasicOpp$Season <- paste(NCAABasicOpp$School, NCAABasicOpp$Year, sep=" ")
NCAABasicOpp = NCAABasicOpp[,c(19,1,18,2:17)]

ncaaB = join(NCAABasic,NCAABasicOpp, by = 'Season', type = 'left', match = 'first')
ncaaB = ncaaB[,c(-35,-36)]

#Scrape Advanced Stats

years = c(2011:2021)
urls = list()
for (i in 1:length(years)) {
  url = paste0('https://www.sports-reference.com/cbb/seasons/', years[i],'-advanced-school-stats.html')
  urls[[i]] = url
}

tbl = list()
years = 2011
j = 1
for (j in seq_along(urls)) {
  tbl[[j]] = urls[[j]] %>%
    read_html() %>%
    html_nodes("table") %>%
    html_table() 
  tbl[[j]]$Year = years
  years = years + 1
}

NCAAAdv = ldply(tbl, data.frame)
NCAAAdv = NCAAAdv[,-c(1,4:21)]

names(NCAAAdv)[names(NCAAAdv) == "Var.2"] <- "School"
names(NCAAAdv)[names(NCAAAdv) == "Overall"] <- "G"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced"] <- "Pace"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.1"] <- "ORtg"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.2"] <- "FTr"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.3"] <- "X3PAr"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.4"] <- "TSPer"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.5"] <- "TRBPer"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.6"] <- "ASTPer"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.7"] <- "STLPer"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.8"] <- "BLKPer"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.9"] <- "eFGPer"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.10"] <- "TOVPer"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.11"] <- "ORBPer"
names(NCAAAdv)[names(NCAAAdv) == "School.Advanced.12"] <- "FT_FGA"

NCAAAdv <- NCAAAdv[!grepl("School", NCAAAdv$School),]
NCAAAdv <- NCAAAdv[!grepl("Overall", NCAAAdv$G),]
NCAAAdv$School <- str_remove(NCAAAdv$School, "NCAA")
NCAAAdv <- NCAAAdv[!grepl(0, NCAAAdv$G),]
NCAAAdv = NCAAAdv[,c(-2)]

NCAAAdv$Season <- paste(NCAAAdv$School, NCAAAdv$Year, sep=" ")
NCAAAdv = NCAAAdv[,c(16,1,15,2:14)]

#Scrape Opp Advanced

years = c(2011:2021)
urls = list()
for (i in 1:length(years)) {
  url = paste0('https://www.sports-reference.com/cbb/seasons/', years[i],'-advanced-school-stats.html')
  urls[[i]] = url
}

tbl = list()
years = 2011
j = 1
for (j in seq_along(urls)) {
  tbl[[j]] = urls[[j]] %>%
    read_html() %>%
    html_nodes("table") %>%
    html_table() 
  tbl[[j]]$Year = years
  years = years + 1
}

NCAAAdvOpp = ldply(tbl, data.frame)
NCAAAdvOpp = NCAAAdvOpp[,-c(1,4:21)]

names(NCAAAdvOpp)[names(NCAAAdvOpp) == "Var.2"] <- "School"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "Overall"] <- "G"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced"] <- "O_Pace"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.1"] <- "O_ORtg"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.2"] <- "OFTr"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.3"] <- "O_3PAr"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.4"] <- "O_TSPer"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.5"] <- "OTRBPer"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.6"] <- "OASTPer"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.7"] <- "OSTLPer"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.8"] <- "OBLKPer"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.9"] <- "OeFGPer"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.10"] <- "OTOVPer"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.11"] <- "O_ORBPer"
names(NCAAAdvOpp)[names(NCAAAdvOpp) == "School.Advanced.12"] <- "OFT_FGA"

NCAAAdvOpp <- NCAAAdvOpp[!grepl("School", NCAAAdvOpp$School),]
NCAAAdvOpp <- NCAAAdvOpp[!grepl("Overall", NCAAAdvOpp$G),]
NCAAAdvOpp$School <- str_remove(NCAAAdvOpp$School, "NCAA")
NCAAAdvOpp <- NCAAAdvOpp[!grepl(0, NCAAAdvOpp$G),]
NCAAAdvOpp = NCAAAdvOpp[,c(-2)]

NCAAAdvOpp$Season <- paste(NCAAAdvOpp$School, NCAAAdvOpp$Year, sep=" ")
NCAAAdvOpp = NCAAAdvOpp[,c(16,1,15,2:14)]

ncaaA = join(NCAAAdv,NCAAAdvOpp, by = 'Season', type = 'left', match = 'first')
ncaaA = ncaaA[,c(-18,-19)]

#Combine Advanced and Basic

ncaa = join(ncaaB,ncaaA, by = 'Season', type = 'left', match = 'first')
ncaa$PPG <- as.numeric(ncaa$TotPTS)/as.numeric(ncaa$G)
ncaa$PAPG <- as.numeric(ncaa$OppPTS)/as.numeric(ncaa$G)
ncaa = ncaa[,c(1,2:13,78,79,16:77)]
head(ncaa)
ncaa = ncaa[,c(-1,-10,-11,-12,-13,-16,-17,-34,-50,-51,-65)]
```

# Game by Game Scores data

```{r}
teams <- str_replace_all(ncaa$School, " ","-")
teams <- str_replace_all(teams, "[)]","")
teams <- str_replace_all(teams, "[&]","")
teams <- str_replace_all(teams, "[']","")
teams <- str_replace_all(teams, "[.]","")
teams <- str_replace_all(teams, "[()]","")
teams <- str_replace_all(teams, "\\s","")
teams <- str_replace_all(teams, "UC-", "california-")
teams <- tolower(teams)
teams <- unique(teams)
teams[290] = "william-mary"
teams[13] = "arkansas-little-rock"
teams[344] = "nebraska-omaha"
teams[40] = "california"
teams[131] = "louisiana-lafayette"
teams[128] = "long-beach-state"
teams[242] = "southern-illinois-edwardsville"
teams[262] = "texas-pan-american"
teams[278] = "virginia-military-institute"
teams[342] = "ipfw"
o2021 <- teams[c(355,356,357)]
o2020 <- teams[354] # merrimack
o2019 <- teams[c(352,353)]
o2014 <- teams[c(348,351,347,349)]
o2013 <- teams[c(344,346)]
u20 <- teams[22] # bethune-cookman
u19 <- teams[c(22,321)] # savannah-state
teams <- teams[-c(22,321,344:346,351,347,348,349,352,353,354,355,356,357)]

years = c(2011:2020)
urls = list()
t=0
for (i in 1:length(years)) {
  for (k in 1:length(teams)) {
    url = paste0('https://www.sports-reference.com/cbb/schools/', teams[k],'/', years[i],'-schedule.html')
    t = t + 1
    urls[[t]] = url
  }
}

for (i in 1:length(o2021)) {
  url = paste0('https://www.sports-reference.com/cbb/schools/', o2021[i],'/2021-schedule.html')
  t = t + 1
  urls[[t]] = url
}

years = c(2020:2021)
for (i in 1:length(years)) {
  url = paste0('https://www.sports-reference.com/cbb/schools/merrimack/', years[i],'-schedule.html')
  t = t + 1
  urls[[t]] = url
}

years = c(2019:2021)
for (i in 1:length(years)) {
  for (k in 1:length(o2019)) {
    url = paste0('https://www.sports-reference.com/cbb/schools/', o2019[k],'/', years[i],'-schedule.html')
    t = t + 1
    urls[[t]] = url
  }
}

years = c(2014:2021)
for (i in 1:length(years)) {
  for (k in 1:length(o2014)) {
    url = paste0('https://www.sports-reference.com/cbb/schools/', o2014[k],'/', years[i],'-schedule.html')
    t = t + 1
    urls[[t]] = url
  }
}

years = c(2013:2021)
for (i in 1:length(years)) {
  for (k in 1:length(o2013)) {
    url = paste0('https://www.sports-reference.com/cbb/schools/', o2013[k],'/', years[i],'-schedule.html')
    t = t + 1
    urls[[t]] = url
  }
}

years = c(2011:2019)
for (i in 1:length(years)) {
  for (k in 1:length(u19)) {
    url = paste0('https://www.sports-reference.com/cbb/schools/', u19[k],'/', years[i],'-schedule.html')
    t = t + 1
    urls[[t]] = url
  }
}

url = 'https://www.sports-reference.com/cbb/schools/bethune-cookman/2020-schedule.html'
t = t + 1
urls[[t]] = url

tbl = list()
j = 1
for (j in seq_along(urls)) {
  tbl[[j]] = urls[[j]] %>%
    read_html %>%  
    html_node('table#polls') %>%
    html_table() %>%
    html_node('table#schedule') %>% 
    html_table() 
}

schedule = ldply(tbl, data.frame)

names(schedule)[names(schedule) == "Date"] <- "Year"
names(schedule)[names(schedule) == "Tm"] <- "aP"
schedule <- schedule[!grepl("Date", schedule$Year),]
schedule$Opponent <- str_remove(schedule$Opponent, "[(]")
schedule$Opponent <- str_remove(schedule$Opponent, "[)]")
schedule$Opponent <- removeNumbers(schedule$Opponent)
#schedule <- schedule %>%
 # select("Opponent","Year","aP")
```




# MODEL WITH TOURNEY

# Read Dataset
```{r}
#ncaa<-read.csv("C:/Users/qschr/OneDrive/Desktop/NCAA/R/Dataset.csv", header =TRUE, sep=",")

#head(ncaa)
```

```{r}
fullmodel<-lm(aP~W.L.+SRS+SOS+PPG+FG.+X3P.+FT.+Pace+ORtg+FTr+X3PAr+TS.+TRB.+AST.+eFG.+TOV.+ORB.+FT.FGA+PAPG+STL.+BLK.+OFG.+O3P.+O.ORtg+OFTr+O3PAr+OTS.+OTRB.+OAST.+OeFG.+OTOV.+Pace.1+O.ORB.+O.FT.FGA, ncaa)
```

```{r}
model1<-lm(aP~SOS+PPG+Pace+PAPG+OFTr+Pace.1+O.FT.FGA, ncaa)

Anova(model1,Type = II)
summary(model1)
```

# BF Test - not significant - No transformation required
```{r}
ncaa$groups <- cut(ncaa$SOS+ncaa$PPG+ncaa$PAPG+ncaa$Pace+ncaa$OFTr+ncaa$Pace.1+ncaa$O.FT.FGA, 5)
ncaa$residuals <- model1$residuals
bf.test(residuals~groups, ncaa)
```
# Outlier Diagnostics
# X outliers if >2*(p/n) - none
# Y outliers if >t(1-.05/(2*256),dfe) - none
# Influential points - none
```{r}
influencePlot(model1)
shapiro.test(residuals(model1))
plot(model1)
```
# Multicollinearity Check - not gucci
```{r}
VIF(lm(SOS~PPG+Pace+PAPG+OFTr+Pace.1+O.FT.FGA, ncaa))
VIF(lm(PPG~SOS+Pace+PAPG+OFTr+Pace.1+O.FT.FGA, ncaa))
VIF(lm(Pace~PPG+SOS+PAPG+OFTr+Pace.1+O.FT.FGA, ncaa))
VIF(lm(PAPG~PPG+Pace+SOS+OFTr+Pace.1+O.FT.FGA, ncaa))
VIF(lm(OFTr~PPG+Pace+PAPG+SOS+Pace.1+O.FT.FGA, ncaa))
VIF(lm(Pace.1~PPG+Pace+PAPG+OFTr+SOS+O.FT.FGA, ncaa))
VIF(lm(O.FT.FGA~PPG+Pace+PAPG+OFTr+Pace.1+SOS, ncaa))
```
# Ridge regression
```{r}
ridge <- lmridge(aP~SOS+PPG+Pace+PAPG+OFTr+Pace.1+O.FT.FGA, ncaa,K=seq(0,0.5,0.01))
#vif(ridge) # K = 0.16
r1 <- lmridge(aP~SOS+PPG+Pace+PAPG+OFTr+Pace.1+O.FT.FGA, ncaa,K=0.16)
summary(r1)
```
# Ridge Diagnostics
```{r}
shapiro.test(residuals(r1))
```



# Without Tourney

```{r}
ncaa2<-read.csv("C:/Users/qschr/OneDrive/Desktop/NCAA/R/Dataset w.o Tourney.csv", header =TRUE, sep=",")

head(ncaa2)
```

```{r}
full<-lm(aP~W.L.+SRS+SOS+PPG+FG.+X3P.+FT.+Pace+ORtg+FTr+X3PAr+TS.+TRB.+AST.+eFG.+TOV.+ORB.+FT.FGA+PAPG+STL.+BLK.+OFG.+O3P.+O.ORtg+OFTr+O3PAr+OTS.+OTRB.+OAST.+OeFG.+OTOV.+Pace.1+O.ORB.+O.FT.FGA, ncaa2)
```

```{r}
mod1<-lm(aP~SOS+PPG+Pace+ORtg+PAPG+O.ORtg+Pace.1, ncaa2)

Anova(mod1,Type = II)
summary(mod1)
```

# Not gucci
```{r}
ncaa2$groups <- cut(ncaa2$SOS+ncaa2$PPG+ncaa2$Pace+ncaa2$ORtg+ncaa2$PAPG+ncaa2$O.ORtg+ncaa2$Pace.1, 5)
ncaa2$residuals <- mod1$residuals
bf.test(residuals~groups, ncaa2)
```
# Gucci
```{r}
influencePlot(model1)
shapiro.test(residuals(model1))
plot(model1)
```

```{r}
VIF(lm(SOS~PPG+Pace+ORtg+PAPG+O.ORtg+Pace.1, ncaa2))
VIF(lm(PPG~SOS+Pace+ORtg+PAPG+O.ORtg+Pace.1, ncaa2))
VIF(lm(Pace~PPG+SOS+ORtg+PAPG+O.ORtg+Pace.1, ncaa2))
VIF(lm(ORtg~PPG+Pace+SOS+PAPG+O.ORtg+Pace.1, ncaa2))
VIF(lm(PAPG~PPG+Pace+ORtg+SOS+O.ORtg+Pace.1, ncaa2))
VIF(lm(O.ORtg~PPG+Pace+ORtg+PAPG+SOS+Pace.1, ncaa2))
VIF(lm(Pace.1~PPG+Pace+ORtg+PAPG+O.ORtg+SOS, ncaa2))
```

```{r}
ridge1 <- lmridge(aP~SOS+PPG+Pace+ORtg+PAPG+O.ORtg+Pace.1, ncaa2,K=seq(0,0.5,0.01))
#vif(ridge1) # K = 0.07
r2 <- lmridge(aP~SOS+PPG+Pace+ORtg+PAPG+O.ORtg+Pace.1, ncaa2,K=0.07)
summary(r2)
```

```{r}
shapiro.test(residuals(r2))
```

